// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: enumproto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Eyecolor int32

const (
	Eyecolor_EYE_COLOR_UNSPECIFIED Eyecolor = 0
	Eyecolor_EYE_COLOR_BLUE        Eyecolor = 1
	Eyecolor_EYE_COLOR_GREEN       Eyecolor = 2
)

// Enum value maps for Eyecolor.
var (
	Eyecolor_name = map[int32]string{
		0: "EYE_COLOR_UNSPECIFIED",
		1: "EYE_COLOR_BLUE",
		2: "EYE_COLOR_GREEN",
	}
	Eyecolor_value = map[string]int32{
		"EYE_COLOR_UNSPECIFIED": 0,
		"EYE_COLOR_BLUE":        1,
		"EYE_COLOR_GREEN":       2,
	}
)

func (x Eyecolor) Enum() *Eyecolor {
	p := new(Eyecolor)
	*p = x
	return p
}

func (x Eyecolor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Eyecolor) Descriptor() protoreflect.EnumDescriptor {
	return file_enumproto_proto_enumTypes[0].Descriptor()
}

func (Eyecolor) Type() protoreflect.EnumType {
	return &file_enumproto_proto_enumTypes[0]
}

func (x Eyecolor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Eyecolor.Descriptor instead.
func (Eyecolor) EnumDescriptor() ([]byte, []int) {
	return file_enumproto_proto_rawDescGZIP(), []int{0}
}

type Enumration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eyecolor Eyecolor `protobuf:"varint,1,opt,name=eyecolor,proto3,enum=example.simple.Eyecolor" json:"eyecolor,omitempty"`
}

func (x *Enumration) Reset() {
	*x = Enumration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enumproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enumration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enumration) ProtoMessage() {}

func (x *Enumration) ProtoReflect() protoreflect.Message {
	mi := &file_enumproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enumration.ProtoReflect.Descriptor instead.
func (*Enumration) Descriptor() ([]byte, []int) {
	return file_enumproto_proto_rawDescGZIP(), []int{0}
}

func (x *Enumration) GetEyecolor() Eyecolor {
	if x != nil {
		return x.Eyecolor
	}
	return Eyecolor_EYE_COLOR_UNSPECIFIED
}

var File_enumproto_proto protoreflect.FileDescriptor

var file_enumproto_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x6e, 0x75, 0x6d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x22, 0x42, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x34, 0x0a, 0x08, 0x65, 0x79, 0x65, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x45, 0x79, 0x65, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x08, 0x65, 0x79, 0x65,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2a, 0x4e, 0x0a, 0x08, 0x45, 0x79, 0x65, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e,
	0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x4c, 0x55, 0x45, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x47, 0x52,
	0x45, 0x45, 0x4e, 0x10, 0x02, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enumproto_proto_rawDescOnce sync.Once
	file_enumproto_proto_rawDescData = file_enumproto_proto_rawDesc
)

func file_enumproto_proto_rawDescGZIP() []byte {
	file_enumproto_proto_rawDescOnce.Do(func() {
		file_enumproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_enumproto_proto_rawDescData)
	})
	return file_enumproto_proto_rawDescData
}

var file_enumproto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enumproto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enumproto_proto_goTypes = []interface{}{
	(Eyecolor)(0),      // 0: example.simple.Eyecolor
	(*Enumration)(nil), // 1: example.simple.enumration
}
var file_enumproto_proto_depIdxs = []int32{
	0, // 0: example.simple.enumration.eyecolor:type_name -> example.simple.Eyecolor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enumproto_proto_init() }
func file_enumproto_proto_init() {
	if File_enumproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enumproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enumration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enumproto_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enumproto_proto_goTypes,
		DependencyIndexes: file_enumproto_proto_depIdxs,
		EnumInfos:         file_enumproto_proto_enumTypes,
		MessageInfos:      file_enumproto_proto_msgTypes,
	}.Build()
	File_enumproto_proto = out.File
	file_enumproto_proto_rawDesc = nil
	file_enumproto_proto_goTypes = nil
	file_enumproto_proto_depIdxs = nil
}
